export const CSV_FIELD_MAP = {
  调研日期: "researchDate",
  市场: "market",
  平台站点: "platformSite",
  关键词: "keyword",
  细分方向: "nicheDirection",
  产品方向: "productDirection",
  ASIN: "asin",
  产品标题: "title",
  品牌: "brand",
  产品链接: "productUrl",
  当前价格: "currentPrice",
  当前BSR: "currentBsr",
  当前评分: "currentRating",
  评论数: "reviewCount",
  "30天评论增长": "reviewGrowth30d",
  核心卖点: "coreSellingPoints",
  高频差评点: "topComplaintPoints",
  高频想要点: "desiredPoints",
  头部垄断程度: "headMonopoly",
  竞争激烈度: "competitionLevel",
  总体风险等级: "overallRisk",
  初筛结论: "initialConclusion",
  下一步动作: "nextAction",
  结论摘要: "conclusionSummary",
} as const;

export const REQUIRED_COLUMNS = [
  "调研日期",
  "市场",
  "平台站点",
  "关键词",
  "产品方向",
  "当前评分",
  "评论数",
  "30天评论增长",
  "头部垄断程度",
  "竞争激烈度",
  "总体风险等级",
] as const;

export const RECOMMENDED_COLUMNS = [
  "当前价格",
  "当前BSR",
  "核心卖点",
  "高频差评点",
  "高频想要点",
] as const;
